### ISSUE TITLE
Issues with MLX90640 thermal camera

### ISSUE THREAD

**Issue by pixelsquared** [TheRealWaldo/thermal#103]
## Version of the thermal_vision
v3.0.0

## Configuration

```yaml
logger:
  default: warn
  logs:
    custom_components.thermal_vision: debug

camera:
  - platform: thermal_vision
    name: "Joshua's Room Thermal Camera"
    host: http://192.168.2.228
    min_temp: 20
    max_temp: 40
    auto_range: false
    preserve_aspect_ratio: false
    overlay: false
    sensor:
      rows: 24
      cols: 32
    interpolate:
      method: linear
      rows: 48
      cols: 64

```

## Describe the bug

I am trying to get the MLX90640 sensor to work with this project.
I have made a custom PlatformIO project to interface with the camera and return similar data to the AMG8833 one.
All I am getting is a purple image.
I am not 100% sure if I am doing something wrong or it is an issue with the project.
Any help would be appreciated.

the result of "http://192.168.2.228/raw"
[raw.json.txt](https://github.com/TheRealWaldo/thermal/files/7454508/raw.json.txt)

Result camera:
![image](https://user-images.githubusercontent.com/10050016/139702568-cc5b9c60-1b6c-46ed-9bef-146284be565a.png)

## Debug log

The only logs I got were with Interpolation method set to bicubic otherwise I don't see any logs

```text

2021-11-01 10:52:36 ERROR (MainThread) [homeassistant.components.camera] Error while setting up thermal_vision platform for camera
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/thermal_vision/camera.py", line 131, in async_setup_platform
async_add_entities([ThermalVisionCamera(config, hass)])
File "/config/custom_components/thermal_vision/camera.py", line 193, in __init__
self._setup_default_image()
File "/config/custom_components/thermal_vision/camera.py", line 320, in _setup_default_image
self._default_image = self._camera_image(
File "/config/custom_components/thermal_vision/camera.py", line 351, in _camera_image
interpolation = interpolate(xi, yi, pixels, xo, yo, self._method)
File "/config/custom_components/thermal_vision/interpolate.py", line 140, in interpolate
return bicubic(xi, yi, values, xo, yo)
File "/config/custom_components/thermal_vision/interpolate.py", line 46, in bicubic
f30 = values[i + 2, j - 1] # row3 col0 >> x0,y3
IndexError: index 24 is out of bounds for axis 0 with size 24

```

**Comment by TheRealWaldo** [comment]
For bicubic interpolation, I believe you require a 1:1 ratio to rows/cols for the algorithm to work.  As for the purple, that's just the default image.

Please give me a little while to mock something up to test as I do not have the same sensor here to try right now.

**Comment by pixelsquared** [comment]
Thanks for looking at this.
I was not familiar with bicubic interpolation.
In the issue I gave a example of the JSON data from the sensor.
If you need any more data from me please just ask.

**Comment by TheRealWaldo** [comment]
@pixelsquared if you remove the interpolate section all-together, what happens?

**Comment by pixelsquared** [comment]
I get this error because it defaults to bicubic interpolation.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_vision/camera.py", line 131, in async_setup_platform
    async_add_entities([ThermalVisionCamera(config, hass)])
  File "/config/custom_components/thermal_vision/camera.py", line 193, in __init__
    self._setup_default_image()
  File "/config/custom_components/thermal_vision/camera.py", line 320, in _setup_default_image
    self._default_image = self._camera_image(
  File "/config/custom_components/thermal_vision/camera.py", line 351, in _camera_image
    interpolation = interpolate(xi, yi, pixels, xo, yo, self._method)
  File "/config/custom_components/thermal_vision/interpolate.py", line 140, in interpolate
    return bicubic(xi, yi, values, xo, yo)
  File "/config/custom_components/thermal_vision/interpolate.py", line 46, in bicubic
    f30 = values[i + 2, j - 1]  # row3 col0 >> x0,y3
IndexError: index 24 is out of bounds for axis 0 with size 24
```

**Comment by TheRealWaldo** [comment]
@pixelsquared, it would appear both methods of interpolation from the original code will only work with 1:1 ratios.  I'll be adding an option to disable the interpolation shortly.

I will look into other interpolation algorithms at a later date.

**Comment by pixelsquared** [comment]
@TheRealWaldo Thanks for the update.

**Comment by TheRealWaldo** [comment]
@pixelsquared new version is going through the paces now.  

Please share your code for the MLX90640; I'd love to link it from the readme!

**Comment by pixelsquared** [comment]
Yep new update seems to be working. :smile:

![image](https://user-images.githubusercontent.com/10050016/139754098-0e9a5c85-cd86-47fb-87b7-a7018c397e6f.png)

I will share the MLX90640 code just want to improve it a bit more first.

**Comment by TheRealWaldo** [comment]
Linked in #112 !
